In [1]:
import numpy as np
arr = np.array([range(5), range(5), range(5)])
print(arr.shape) # fill in the blank property name
# prints out the tuple, (3, 5)

(3, 5)


In [3]:
data = np.arange(32).reshape(8,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [5]:
a = np.array([[11, 22, 33],
 [44, 55, 66],
 [77, 88, 99]] )
a[0:2, 1]

array([22, 55])

In [6]:
data = np.array([[0, 1, 2],
 [3, 4, 5],
 [6, 7, 8]])
data[[1, 1, 1, 0]]

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5],
       [0, 1, 2]])

In [8]:
a = np.array([[11, 22, 33],
 [44, 55, 66],
 [77, 88, 99]])
a[[1, 0]]

array([[44, 55, 66],
       [11, 22, 33]])

In [13]:
nested = np.array([
    [[1, 2], 
     [3, 4]], 

    [[5, 6], 
     [7, 8]]])
nested[:,:] = 480
nested

array([[[480, 480],
        [480, 480]],

       [[480, 480],
        [480, 480]]])

In [14]:
data = np.array([[ 0,  1,  2,  3],
 [ 4,  5,  6,  7],
 [ 8,  9, 10, 11]])
data.mean(axis=0)

array([4., 5., 6., 7.])

In [18]:
data = [119, 111, 137, 144, 134, 159, 142, 147, 164, 142, 129, 145, 157, 152, 146]
np.sqrt(np.var(data, ddof = 1))

14.391796605143135

In [19]:
counts = {}

for item in data:
      if item in counts:
           counts[item] += 1
      else:
          counts[item] = 1
	
print(sorted(counts.items(), key=lambda t: t[1])[-1])
print(max(counts.items(), key=lambda t: t[1]))
print(sorted(counts.items(), key=lambda t: t[1]))
print(max(counts))
print(max(counts.items(), key=lambda t: t[0]))

(142, 2)
(142, 2)
[(119, 1), (111, 1), (137, 1), (144, 1), (134, 1), (159, 1), (147, 1), (164, 1), (129, 1), (145, 1), (157, 1), (152, 1), (146, 1), (142, 2)]
164
(164, 1)
